version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: assignment-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: assignment_db_dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

  # Backend Server (Development)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: assignment-server-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: mongodb://admin:password123@mongodb:27017/assignment_db_dev?authSource=admin
      JWT_SECRET: dev-jwt-secret-key
      PORT: 5001
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  # Frontend Client (Development)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: assignment-client-dev
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5001/api
      CHOKIDAR_USEPOLLING: true
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

volumes:
  mongodb_dev_data:
    driver: local

networks:
  app-network:
    driver: bridge
